table FACT_ANSWERS
	lineageTag: 9717762e-33ad-4b09-954b-a7f0f35d106b

	measure RatioQuestionsAnswers = DISTINCTCOUNT(FACT_ANSWERS[ANSWER_ID])/DISTINCTCOUNT(FACT_ANSWERS[QUESTION_ID])
		displayFolder: Measures
		lineageTag: d5190fe1-d044-4e76-bf4f-971b0aab9e47

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MaxScore =
			CALCULATE(
			    MAX(ANSWER[MAX_WEIGHT]),
			    ALL(SITE),
			    ALL(CAMPAIGN)
			)
		formatString: 0
		displayFolder: Measures
		lineageTag: efa4c691-ab7a-4074-8bf1-fd92583ab15e

	measure Score = ```
			DIVIDE(
			    SUMX(FACT_ANSWERS,FACT_ANSWERS[WEIGHT])+0, 
			    FACT_ANSWERS[MaxScore]
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Measures
		lineageTag: 52dd8bcc-22a8-4c7d-971f-abb580febbdd

	measure 'Surface Au Sol'
		displayFolder: Measures
		lineageTag: 33cb2172-a02f-4e3f-86b7-f33e3248fe4c

	measure NombreQuestionnairesRemplis =
			
			CALCULATE(
			    DISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID]),
			    CAMPAIGN_SITE[IS_FINISHED] = 1
			)
		formatString: 0
		displayFolder: Measures
		lineageTag: f3c82865-5412-45bb-a044-a329daf77670

	measure NombreTotalQuestionnairesEnvoyes =
			
			CALCULATE(
				DISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID])
			)
		formatString: 0
		displayFolder: Measures
		lineageTag: 0d5d9c6c-8b63-47de-bec7-a0fb7671edb8

	measure RatioRemplisPourcentage =
			
			DIVIDE(
			    [NombreQuestionnairesRemplis],
			    [NombreTotalQuestionnairesEnvoyes]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Measures
		lineageTag: 7dbd4d17-7b0d-42f0-9e4e-d8caf9323aea

	measure 'NombreQuestionnairesRemplis total for CAMPAIGN_SITE_ID' =
			
			CALCULATE(
				DISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID])
			)
		formatString: 0
		displayFolder: Measures
		lineageTag: f5326679-0a79-495e-9a48-b6fb0f954ad2

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "TotalForSelectedCategory"
				}

		changedProperty = FormatString

	measure TotalPointsDisponibles =
			
			SUMX(
			    ANSWER,
			    IF(
			        ANSWER[IS_NA] = 0,
			        ANSWER[WEIGHT],
			        0
			    )
			)
		displayFolder: Measures
		lineageTag: ab03ba9b-58ce-4c3e-b711-a7641f6a6f1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalPointsObtenus =
			
			SUM(FACT_ANSWERS[WEIGHT])
		displayFolder: Measures
		lineageTag: b252eedf-d8c3-45e3-b85f-ace7604cb99f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScoreMoyenGlobalPourcentage =
			
			DIVIDE(
			    [TotalPointsObtenus],
			    [TotalPointsDisponibles],
			    0
			) * 100
		displayFolder: Measures
		lineageTag: 124b84bd-039d-4190-9cba-2ca842cdb7b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NombreReponsesParQuestion =
			
			VAR QuestionSelectionnee = SELECTEDVALUE(QUESTION[ID])
			RETURN
			    IF(
			        ISBLANK(QuestionSelectionnee),
			        0, -- Si aucune question n'est sélectionnée
			        IF(
			            CALCULATE(COUNTROWS(ANSWER), FACT_ANSWERS[QUESTION_ID] = QuestionSelectionnee) = 0,
			            0, -- Si la question sélectionnée n'a pas de réponse
			            CALCULATE(COUNTROWS(ANSWER), FACT_ANSWERS[QUESTION_ID] = QuestionSelectionnee) -- Retourne le nombre de réponses
			        )
			    )
		formatString: 0
		displayFolder: Measures
		lineageTag: fcd8a9ef-1b35-4377-90fd-ca1ca40e78ac

	measure TotalResponses = ```
			
			VAR FilteredAnswers =
			    FILTER(
			        'FACT_ANSWERS',
			        'FACT_ANSWERS'[QUESTION_ID] IN 
			            SELECTCOLUMNS(FILTER('QUESTION', 'QUESTION'[CODE] >= "ID.010" && 'QUESTION'[CODE] <= "ID.018"), "QUESTION_ID", 'QUESTION'[ID])
			    )
			RETURN
			    SUMX(
			        FilteredAnswers,
			        IFERROR(VALUE('FACT_ANSWERS'[ANSWER_VALUE]), 0)
			    )
			```
		displayFolder: Measures
		lineageTag: 4e49ca2f-c889-4f86-b373-6ab268b43cf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MoyenneScoresParPillier =
			
			CALCULATE(
			    AVERAGEX(
			        FILTER(FACT_ANSWERS, FACT_ANSWERS[PILLAR_ID] = SELECTEDVALUE(PILLAR[ID])),
			        FACT_ANSWERS[WEIGHT]
			    )
			)
		displayFolder: Measures
		lineageTag: cc3d0aef-88fc-4ee6-9240-3257c834270b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MoyenneScoresParPillier_Site =
			
			CALCULATE(
			    AVERAGEX(
			        FILTER(
			            FACT_ANSWERS,
			            FACT_ANSWERS[PILLAR_ID] = SELECTEDVALUE(PILLAR[ID]) &&
			            FACT_ANSWERS[SITE_ID] = SELECTEDVALUE(SITE[ID])
			        ),
			        FACT_ANSWERS[WEIGHT]
			    )
			)
		displayFolder: Measures
		lineageTag: ced56a2f-3527-4120-b1a9-d1493ca8b6e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AvgScore = CALCULATE(AVERAGEX(FACT_ANSWERS,FACT_ANSWERS[Score]), KEEPFILTERS('LANGUAGE'))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Measures
		lineageTag: 7a105a96-7823-4009-b706-cd9a050d3abc

	column COUNTRY_ID
		dataType: string
		displayFolder: Details
		lineageTag: c7aeef56-a06d-4c2a-81af-f5dbc553761b
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

	column SITE_ID
		dataType: string
		displayFolder: Details
		lineageTag: fae01c71-f0f1-4d00-84a4-7f4f96600e63
		summarizeBy: none
		sourceColumn: SITE_ID

		annotation SummarizationSetBy = Automatic

	column CAMPAIGN_ID
		dataType: string
		displayFolder: Details
		lineageTag: d71a60bb-a2db-43bc-993a-115e45379f71
		summarizeBy: none
		sourceColumn: CAMPAIGN_ID

		annotation SummarizationSetBy = Automatic

	column PILLAR_ID
		dataType: string
		displayFolder: Details
		lineageTag: c88211f2-476b-4dca-a0eb-2bb539247d1e
		summarizeBy: none
		sourceColumn: PILLAR_ID

		annotation SummarizationSetBy = Automatic

	column THEME_ID
		dataType: string
		displayFolder: Details
		lineageTag: f7335d96-fca2-4150-93d8-3670a9c97c3c
		summarizeBy: none
		sourceColumn: THEME_ID

		annotation SummarizationSetBy = Automatic

	column CATEGORY_ID
		dataType: string
		displayFolder: Details
		lineageTag: 979dfb0b-bffe-41a3-86c2-14a290cd95bf
		summarizeBy: none
		sourceColumn: CATEGORY_ID

		annotation SummarizationSetBy = Automatic

	column QUESTION_ID
		dataType: string
		displayFolder: Details
		lineageTag: 14cfd092-9c20-40bd-a44b-1917e16fa0a6
		summarizeBy: none
		sourceColumn: QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column ANSWER_ID
		dataType: string
		displayFolder: Details
		lineageTag: 23f3cffc-4f94-40e7-a4db-97b56c742f1e
		summarizeBy: none
		sourceColumn: ANSWER_ID

		annotation SummarizationSetBy = Automatic

	column WEIGHT
		dataType: int64
		displayFolder: Details
		lineageTag: 904109e8-c619-4fae-a3f2-c72b9b3addcd
		summarizeBy: none
		sourceColumn: WEIGHT

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAMPAIGN_SITE_ID
		dataType: string
		displayFolder: Details
		lineageTag: 6f5e9951-0ba1-4f59-a777-a44aff7518a7
		summarizeBy: none
		sourceColumn: CAMPAIGN_SITE_ID

		annotation SummarizationSetBy = Automatic

	column ANSWER_VALUE
		dataType: string
		displayFolder: Details
		lineageTag: 96a11b2a-d1cd-4dd9-a75c-497f50768dd4
		summarizeBy: none
		sourceColumn: ANSWER_VALUE

		annotation SummarizationSetBy = Automatic

	partition FACT_ANSWERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("UY39352-IDLOGISTICS.snowflakecomputing.com","WH_DEV_GRP"),
				    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind="Database"]}[Data],
				    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name="DWH_SUSTAIN_ID",Kind="Schema"]}[Data],
				    FACT_ANSWERS_Table = DWH_SUSTAIN_ID_Schema{[Name="FACT_ANSWERS",Kind="Table"]}[Data]
				in
				    FACT_ANSWERS_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

