table FACT_ANSWERS
	lineageTag: 9717762e-33ad-4b09-954b-a7f0f35d106b

	measure RatioQuestionsAnswers = DISTINCTCOUNT(FACT_ANSWERS[ANSWER_ID])/DISTINCTCOUNT(FACT_ANSWERS[QUESTION_ID])
		lineageTag: d5190fe1-d044-4e76-bf4f-971b0aab9e47

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MaxScore = MAX(FACT_ANSWERS[WEIGHT])
		lineageTag: efa4c691-ab7a-4074-8bf1-fd92583ab15e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SCORE = ```
			DIVIDE(
			    SUM(FACT_ANSWERS[WEIGHT]), 
			    FACT_ANSWERS[MaxScore]
			)
			```
		lineageTag: 52dd8bcc-22a8-4c7d-971f-abb580febbdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SommeID010
		lineageTag: 33cb2172-a02f-4e3f-86b7-f33e3248fe4c

	measure NombreQuestionnairesRemplis =
			
			CALCULATE(
			    COUNTROWS(FACT_ANSWERS),
			    CAMPAIGN_SITE[IS_FINISHED] = 1
			)
		formatString: 0
		lineageTag: f3c82865-5412-45bb-a044-a329daf77670

	measure NombreTotalQuestionnairesEnvoyes =
			
			COUNTROWS(FACT_ANSWERS)
		formatString: 0
		lineageTag: 0d5d9c6c-8b63-47de-bec7-a0fb7671edb8

	measure RatioRemplisPourcentage =
			
			DIVIDE(
			    [NombreQuestionnairesRemplis],
			    [NombreTotalQuestionnairesEnvoyes],
			    0
			) * 100
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7dbd4d17-7b0d-42f0-9e4e-d8caf9323aea

	measure 'NombreQuestionnairesRemplis total for CAMPAIGN_SITE_ID' =
			
			CALCULATE(
				[NombreQuestionnairesRemplis],
				ALLSELECTED('FACT_ANSWERS'[CAMPAIGN_SITE_ID])
			)
		formatString: 0
		lineageTag: f5326679-0a79-495e-9a48-b6fb0f954ad2

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "TotalForSelectedCategory"
				}

		changedProperty = FormatString

	measure TotalPointsDisponibles =
			
			SUMX(
			    ANSWER,
			    IF(
			        ANSWER[IS_NA] = 0,
			        ANSWER[WEIGHT],
			        0
			    )
			)
		lineageTag: ab03ba9b-58ce-4c3e-b711-a7641f6a6f1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalPointsObtenus =
			
			SUM(FACT_ANSWERS[WEIGHT])
		lineageTag: b252eedf-d8c3-45e3-b85f-ace7604cb99f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScoreMoyenGlobalPourcentage =
			
			DIVIDE(
			    [TotalPointsObtenus],
			    [TotalPointsDisponibles],
			    0
			) * 100
		lineageTag: 124b84bd-039d-4190-9cba-2ca842cdb7b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTRY_ID
		dataType: string
		lineageTag: c7aeef56-a06d-4c2a-81af-f5dbc553761b
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

	column SITE_ID
		dataType: string
		lineageTag: fae01c71-f0f1-4d00-84a4-7f4f96600e63
		summarizeBy: none
		sourceColumn: SITE_ID

		annotation SummarizationSetBy = Automatic

	column CAMPAIGN_ID
		dataType: string
		lineageTag: d71a60bb-a2db-43bc-993a-115e45379f71
		summarizeBy: none
		sourceColumn: CAMPAIGN_ID

		annotation SummarizationSetBy = Automatic

	column PILLAR_ID
		dataType: string
		lineageTag: c88211f2-476b-4dca-a0eb-2bb539247d1e
		summarizeBy: none
		sourceColumn: PILLAR_ID

		annotation SummarizationSetBy = Automatic

	column THEME_ID
		dataType: string
		lineageTag: f7335d96-fca2-4150-93d8-3670a9c97c3c
		summarizeBy: none
		sourceColumn: THEME_ID

		annotation SummarizationSetBy = Automatic

	column CATEGORY_ID
		dataType: string
		lineageTag: 979dfb0b-bffe-41a3-86c2-14a290cd95bf
		summarizeBy: none
		sourceColumn: CATEGORY_ID

		annotation SummarizationSetBy = Automatic

	column QUESTION_ID
		dataType: string
		lineageTag: 14cfd092-9c20-40bd-a44b-1917e16fa0a6
		summarizeBy: none
		sourceColumn: QUESTION_ID

		annotation SummarizationSetBy = Automatic

	column TEXT_ANSWER
		dataType: string
		lineageTag: 29fd5703-2b4b-4ea6-867d-222b451ed726
		summarizeBy: none
		sourceColumn: TEXT_ANSWER

		annotation SummarizationSetBy = Automatic

	column ANSWER_ID
		dataType: string
		lineageTag: 23f3cffc-4f94-40e7-a4db-97b56c742f1e
		summarizeBy: none
		sourceColumn: ANSWER_ID

		annotation SummarizationSetBy = Automatic

	column WEIGHT
		dataType: double
		lineageTag: 904109e8-c619-4fae-a3f2-c72b9b3addcd
		summarizeBy: none
		sourceColumn: WEIGHT

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAMPAIGN_SITE_ID
		dataType: string
		lineageTag: 6f5e9951-0ba1-4f59-a777-a44aff7518a7
		summarizeBy: none
		sourceColumn: CAMPAIGN_SITE_ID

		annotation SummarizationSetBy = Automatic

	partition FACT_ANSWERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("UY39352-IDLOGISTICS.snowflakecomputing.com","WH_DEV_GRP"),
				    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind="Database"]}[Data],
				    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name="DWH_SUSTAIN_ID",Kind="Schema"]}[Data],
				    FACT_ANSWERS_Table = DWH_SUSTAIN_ID_Schema{[Name="FACT_ANSWERS",Kind="Table"]}[Data]
				in
				    FACT_ANSWERS_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

