table SITE
	lineageTag: 2381ef30-e632-430f-ac21-7363fac02a4a

	column ID
		dataType: string
		lineageTag: bec9b009-336f-4860-9c9b-ce07b7255dc6
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column NAME
		dataType: string
		lineageTag: 7a950155-1552-42cc-8d24-4289f9fb8217
		summarizeBy: none
		sourceColumn: NAME

		annotation SummarizationSetBy = Automatic

	column COUNTRY_ID
		dataType: string
		lineageTag: 07acce01-15f3-41a0-b273-6fd95b4e0496
		summarizeBy: none
		sourceColumn: COUNTRY_ID

		annotation SummarizationSetBy = Automatic

	column CREATED_BY
		dataType: string
		lineageTag: f62a5a21-bfa4-4e67-97c9-689b42ed2909
		summarizeBy: none
		sourceColumn: CREATED_BY

		annotation SummarizationSetBy = Automatic

	column UPDATED_BY
		dataType: string
		lineageTag: 951c7edf-b223-4138-b066-aff0e3f30b3c
		summarizeBy: none
		sourceColumn: UPDATED_BY

		annotation SummarizationSetBy = Automatic

	column DELETED_BY
		dataType: string
		lineageTag: 9d52072d-6bce-43ea-918c-3b815ba4586a
		summarizeBy: none
		sourceColumn: DELETED_BY

		annotation SummarizationSetBy = Automatic

	column CREATED_AT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 36857969-3775-4966-a999-e962d66d5e5e
		summarizeBy: none
		sourceColumn: CREATED_AT

		variation Variation
			isDefault
			relationship: 55edb667-edd3-410f-9567-143fbbef24e7
			defaultHierarchy: LocalDateTable_fb379a9a-0bf5-477c-8453-1f140d0c3539.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UPDATED_AT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57095c67-fece-4678-b855-dba063e50f8b
		summarizeBy: none
		sourceColumn: UPDATED_AT

		variation Variation
			isDefault
			relationship: 77d15f1b-d0c8-4d0e-a4cd-d59556237534
			defaultHierarchy: LocalDateTable_c6465fdb-b02d-44ac-b784-1fc5412bfb9d.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DELETED_AT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 15d3833b-5770-4828-9c7b-7c94161022be
		summarizeBy: none
		sourceColumn: DELETED_AT

		variation Variation
			isDefault
			relationship: 06fbaa90-212c-4028-8cc1-924346aa3ea7
			defaultHierarchy: LocalDateTable_9214fa93-1e18-4f5b-8469-4ea75dbea0fd.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column COUNTRY_NAME
		dataType: string
		lineageTag: 1d4c2e81-4a21-472a-bef0-71aff061c0a9
		summarizeBy: none
		sourceColumn: COUNTRY_NAME

		annotation SummarizationSetBy = Automatic

	partition SITE = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("idlogistics.west-europe.azure.snowflakecomputing.com","WH_PRD_GRP"),
				    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind="Database"]}[Data],
				    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name="DWH_SUSTAIN_ID",Kind="Schema"]}[Data],
				    SITE_Table = DWH_SUSTAIN_ID_Schema{[Name="SITE",Kind="Table"]}[Data],
				    #"Duplicated Column" = Table.DuplicateColumn(SITE_Table, "COUNTRY_ID", "COUNTRY_ID - Copy"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column",{"ID", "NAME", "COUNTRY_ID", "COUNTRY_ID - Copy", "CREATED_BY", "UPDATED_BY", "DELETED_BY", "CREATED_AT", "UPDATED_AT", "DELETED_AT"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"COUNTRY_ID - Copy", "COUNTRY_NAME"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","3","Germany",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","5","Benelux",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","6","Iberia",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","11","Brazil",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","12","Chile",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","1","Argentina",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","2","France",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","4","United Kingdom",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","9","Italy",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","7","Poland",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","8","Romania",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","Argentina0","Argentina",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","ArgentinaBenelux","Reunion Island",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","ArgentinaUnited Kingdom","Taiwan",Replacer.ReplaceText,{"COUNTRY_NAME"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","ArgentinaGermany","Indonesia",Replacer.ReplaceText,{"COUNTRY_NAME"})
				in
				    #"Replaced Value14"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

