version: 2

sources:
  - name: DWH_SUSTAIN_ID
    database: "{{'DB_PRD_GRP' if target.name == 'prd'  else 'DB_DEV_GRP'}}"
    schema: DWH_SUSTAIN_ID
    tables:
      - name: SITE
      - name: QUESTION
      - name: ANSWER
      - name: ANSWER_EVALUATION
      - name: CAMPAIGN
      - name: CAMPAIGN_SITE
      - name: COUNTRY
      - name: LANGUAGE
      - name: CATEGORY
      - name: THEME
      - name: PILLAR
      - name: LANGUAGE_ANSWER
      - name: LANGUAGE_QUESTION 
      - name: LANGUAGE_PILLAR 
      - name: LANGUAGE_CATEGORY 
      - name: LANGUAGE_THEME 
      - name: EVALUATION 
      - name: SUSTAIN_ID_ACCESS

        
