{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DB_NAME\",\"ANSWER\",\"CAMPAIGN_SITE\",\"CATEGORY\",\"CAMPAIGN\",\"COUNTRY\",\"PILLAR\",\"QUESTION\",\"SITE\",\"THEME\",\"FACT_ANSWERS\",\"LANGUAGE_ANSWER\",\"LANGUAGE_QUESTION\",\"LANGUAGE\",\"LANGUAGE_PILLAR\",\"DATE\",\"LANGUAGE_CATEGORY\",\"LANGUAGE_THEME\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1451.0 (25.03)+5007b75f0f7edbed506e31fcb76584cd6d711788"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "fr-FR",
    "cultures": [
      {
        "name": "fr-FR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DB_NAME",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DB_DEV_GRP\" meta [IsParameterQuery=true, List={\"DB_DEV_GRP\", \"DB_PRD_GRP\"}, DefaultValue=\"DB_DEV_GRP\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9b895a7c-630d-4b28-9536-ba1c6e647a61"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_70640d94-c539-456a-80fc-5935e479a1a7",
        "fromColumn": "SITE_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "SITE"
      },
      {
        "name": "AutoDetected_2de93a95-ccef-48ae-8087-72de9e7e2a80",
        "fromColumn": "QUESTION_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "QUESTION"
      },
      {
        "name": "AutoDetected_1616b1c2-adc8-408e-8387-8acac5d0635b",
        "fromColumn": "CAMPAIGN_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "CAMPAIGN"
      },
      {
        "name": "AutoDetected_7ea20fce-9465-4ea2-92e8-12fc15bdc4db",
        "fromColumn": "CATEGORY_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "CATEGORY"
      },
      {
        "name": "AutoDetected_689489fa-99cb-447d-acf3-a3bf5888f3cd",
        "fromColumn": "PILLAR_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "PILLAR"
      },
      {
        "name": "AutoDetected_0345060a-e0b0-4be5-b5c3-bf55d991252f",
        "fromColumn": "THEME_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "THEME"
      },
      {
        "name": "ab617b0b-b688-b8a2-f052-d763e448bc96",
        "fromColumn": "COUNTRY_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "COUNTRY"
      },
      {
        "name": "AutoDetected_4471e2d8-3610-4efa-b7ba-2872bbadd39b",
        "fromColumn": "CAMPAIGN_SITE_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "CAMPAIGN_SITE"
      },
      {
        "name": "AutoDetected_836a7787-185b-4829-b083-4add3ae8ba0d",
        "fromColumn": "ANSWER_ID",
        "fromTable": "FACT_ANSWERS",
        "toColumn": "ID",
        "toTable": "ANSWER"
      },
      {
        "name": "AutoDetected_2f9e5faf-fd7a-41d8-ad64-43b293b77bc3",
        "fromColumn": "LANGUAGE_ID",
        "fromTable": "LANGUAGE_ANSWER",
        "toColumn": "ID",
        "toTable": "LANGUAGE"
      },
      {
        "name": "AutoDetected_65c875c2-cd8f-44f9-b010-0933d7dbb3a8",
        "fromColumn": "LANGUAGE_ID",
        "fromTable": "LANGUAGE_QUESTION",
        "toColumn": "ID",
        "toTable": "LANGUAGE"
      },
      {
        "name": "AutoDetected_5100420e-61fa-45bb-b0ec-a5f27c49eefa",
        "fromColumn": "LANGUAGE_ID",
        "fromTable": "LANGUAGE_PILLAR",
        "toColumn": "ID",
        "toTable": "LANGUAGE"
      },
      {
        "name": "af460bad-c63e-3dd7-aa17-d808b1ee9aa7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "END_DATE_ID",
        "fromTable": "CAMPAIGN",
        "toColumn": "DATE_ID",
        "toTable": "DATE"
      },
      {
        "name": "1a51e6c4-4d5a-5283-2b8b-3a2fa1503e5d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PILLAR_ID",
        "fromTable": "LANGUAGE_PILLAR",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "ID",
        "toTable": "PILLAR"
      },
      {
        "name": "ad23ab54-0246-d725-b91f-83b72f5c2b45",
        "fromColumn": "ANSWER_ID",
        "fromTable": "LANGUAGE_ANSWER",
        "isActive": false,
        "toColumn": "ID",
        "toTable": "ANSWER"
      },
      {
        "name": "0c12016c-6d7f-342d-4b04-ded997576725",
        "fromColumn": "QUESTION_ID",
        "fromTable": "LANGUAGE_QUESTION",
        "isActive": false,
        "toColumn": "ID",
        "toTable": "QUESTION"
      },
      {
        "name": "AutoDetected_4559b00b-9404-4ac1-9ab8-5b0f63506b5c",
        "fromColumn": "CATEGORY_ID",
        "fromTable": "LANGUAGE_CATEGORY",
        "toColumn": "ID",
        "toTable": "CATEGORY"
      },
      {
        "name": "AutoDetected_c4fb894c-7d6c-4086-af7a-b897e368abf3",
        "fromColumn": "THEME_ID",
        "fromTable": "LANGUAGE_THEME",
        "toColumn": "ID",
        "toTable": "THEME"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "CAMPAIGN_SITE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e678d4b8-082b-4619-9fa8-0a49a41c99f7",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "SITE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4060629-6b56-42b3-858a-66191dec7569",
            "sourceColumn": "SITE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CAMPAIGN_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77d2c268-f242-4b85-a231-1fec8fc37153",
            "sourceColumn": "CAMPAIGN_ID",
            "summarizeBy": "none"
          },
          {
            "name": "IS_FINISHED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5e6468d-dbcb-499c-92f2-427127435de6",
            "sourceColumn": "IS_FINISHED",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd50d78a-90f9-47d1-9340-24e990bedde1",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ecb7ef5e-f0bf-46ce-bfb4-d703898403a4",
        "partitions": [
          {
            "name": "CAMPAIGN_SITE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    CAMPAIGN_SITE_Table = DWH_SUSTAIN_ID_Schema{[Name=\"CAMPAIGN_SITE\",Kind=\"Table\"]}[Data]",
                "in",
                "    CAMPAIGN_SITE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CATEGORY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1829eaaf-2f9f-4328-978e-713bdf7b48bb",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a39ab7a1-64ed-41b2-ade5-16e8c73d02c3",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "576d14f5-f955-4b9c-851e-74a62d7a164f",
            "sourceColumn": "ORDER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "10dee437-28cb-4d8a-93f7-8d8815a171a9",
        "measures": [
          {
            "name": "Translated category",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES(LANGUAGE_CATEGORY[VALUE])),",
              "    FILTER(",
              "        LANGUAGE_CATEGORY,",
              "        LANGUAGE_CATEGORY[LANGUAGE_ID] = SELECTEDVALUE('LANGUAGE'[ID])",
              "    ),",
              "    USERELATIONSHIP(CATEGORY[ID], LANGUAGE_CATEGORY[CATEGORY_ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5fb621ab-6076-4e47-bb5a-9fdf02db72ce"
          }
        ],
        "partitions": [
          {
            "name": "CATEGORY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    CATEGORY_Table = DWH_SUSTAIN_ID_Schema{[Name=\"CATEGORY\",Kind=\"Table\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(CATEGORY_Table,{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CAMPAIGN",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ada3662f-f226-4076-ba8b-9bb23bf34982",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39ed6761-a3c1-42d3-bf95-d285909230a8",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "START_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "965a525d-6343-472d-b4b5-a2c78c7d8d28",
            "sourceColumn": "START_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "END_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a9a9a36e-bc05-47f0-8e55-3cae2011e37a",
            "sourceColumn": "END_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "IS_GLOBAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0e1f0d35-50b4-48c5-8787-283eebf710e8",
            "sourceColumn": "IS_GLOBAL",
            "summarizeBy": "none"
          },
          {
            "name": "END_DATE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f1eb598d-bd60-450f-836c-87224517b2a5",
            "sourceColumn": "END_DATE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "START_DATE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "00e5b6d3-e8be-44fb-ad76-c7f10b32e986",
            "sourceColumn": "START_DATE_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "576ebbc1-b28e-428f-9ab0-86c7c4a41d25",
        "partitions": [
          {
            "name": "CAMPAIGN",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    CAMPAIGN_Table = DWH_SUSTAIN_ID_Schema{[Name=\"DIM_CAMPAIGN\",Kind=\"Table\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(CAMPAIGN_Table,{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "COUNTRY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc1ecd12-ec3c-451f-bd59-eb7d2d6314c8",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "SURNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92a321ab-ad26-4f8b-aca5-fd4271d94b95",
            "sourceColumn": "SURNAME",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ba0835e-8974-43e5-afcc-3165dee31233",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "Img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    COUNTRY[SURNAME],",
              "    \"France\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "    \"Argentina\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "    \"United Kingdom\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAA7DAAAO\",",
              "\"Brazil\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Chile\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Germany\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Indonesia\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Benelux\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Poland\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Romania\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Iberia\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Taiwan\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"United States\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\",",
              "\"Reunion Island\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAADAFBMVEX/AP/7+wLw\",",
              "\"Italy\",\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhk\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "788cd432-3269-4a70-a4da-c28763a8111d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "1cda4c68-f847-4d6a-bed0-f2dbd38398b8",
        "partitions": [
          {
            "name": "COUNTRY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    COUNTRY_Table = DWH_SUSTAIN_ID_Schema{[Name=\"COUNTRY\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(COUNTRY_Table, each [NAME] <> null and [NAME] <> \"\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"Benelux\",\"Belgium\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Brasil\",\"Brazil\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Iberia\",\"Spain\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"United-Kingdom\",\"United Kingdom\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Replaced Value3\", \"NAME\", \"NAME - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"ID\", \"NAME\", \"NAME - Copy\", \"START_DATE\", \"END_DATE\", \"CREATED_AT\", \"UPDATED_AT\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Reordered Columns\",\"Spain\",\"Iberia\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Belgium\",\"Benelux\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value5\",{{\"NAME\", \"SURNAME\"}, {\"NAME - Copy\", \"NAME\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns\",{\"ID\", \"NAME\", \"SURNAME\", \"START_DATE\", \"END_DATE\", \"CREATED_AT\", \"UPDATED_AT\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Reordered Columns1\",\"Reunion Island\",\"Mayotte\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"Belgium\",\"Netherlands\",Replacer.ReplaceText,{\"NAME\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Replaced Value7\",{\"START_DATE\", \"END_DATE\", \"CREATED_AT\", \"UPDATED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PILLAR",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0398e9a8-f8ce-49ea-b707-a1d2b9bcefbb",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66a35bd3-d1d7-4fdf-a775-33a24616799e",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "IS_SITE_INFORMATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f61d0d05-dccc-4c7f-8140-7de3ac869c30",
            "sourceColumn": "IS_SITE_INFORMATION",
            "summarizeBy": "none"
          },
          {
            "name": "ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "285fb8fe-646c-412c-ad4b-28a430506907",
            "sourceColumn": "ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c19fe176-9100-4e64-b0f7-335dd7feb694",
        "measures": [
          {
            "name": "Translated pillar",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES(LANGUAGE_PILLAR[VALUE])),",
              "    FILTER(",
              "        LANGUAGE_PILLAR,",
              "        LANGUAGE_PILLAR[LANGUAGE_ID] = SELECTEDVALUE('LANGUAGE'[ID])",
              "    ),",
              "    USERELATIONSHIP(PILLAR[ID], LANGUAGE_PILLAR[PILLAR_ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "83f88c26-335e-40f9-af14-7f25ee3416f9"
          }
        ],
        "partitions": [
          {
            "name": "PILLAR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    PILLAR_Table = DWH_SUSTAIN_ID_Schema{[Name=\"PILLAR\",Kind=\"Table\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(PILLAR_Table,{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "QUESTION",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c3d7efb-9abc-4900-a3b9-6daf25072db3",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3420c624-584f-40b4-99fe-d72826f0e407",
            "sourceColumn": "CODE",
            "summarizeBy": "none"
          },
          {
            "name": "LABEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3023ac4-c2ff-467c-91b6-767ca6be140e",
            "sourceColumn": "LABEL",
            "summarizeBy": "none"
          },
          {
            "name": "SHORT_LABEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cee6e482-bbed-43b5-8e1b-9fb0a04e6061",
            "sourceColumn": "SHORT_LABEL",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0168dd8-f5eb-472f-9df7-50149fa83d8d",
            "sourceColumn": "DESCRIPTION",
            "summarizeBy": "none"
          },
          {
            "name": "TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b62ba126-2a83-4205-9bf3-2fa349542bbf",
            "sourceColumn": "TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "THEME_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daa74218-a66a-4dd5-a515-f841c94bbd4e",
            "sourceColumn": "THEME_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "104a2bdb-1118-499f-a96a-eed16f41d196",
            "sourceColumn": "CATEGORY_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "37b0b0bb-a454-46d4-b02d-b12efdcfb59d",
        "measures": [
          {
            "name": "Translated label",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES(LANGUAGE_QUESTION[LABEL])),",
              "    FILTER(",
              "        LANGUAGE_QUESTION,",
              "        LANGUAGE_QUESTION[LANGUAGE_ID] = SELECTEDVALUE('LANGUAGE'[ID])",
              "    ),",
              "    USERELATIONSHIP(QUESTION[ID], LANGUAGE_QUESTION[QUESTION_ID])",
              ")"
            ],
            "lineageTag": "3f958586-a7af-4d37-bae7-f12b4d6d5ba4"
          }
        ],
        "partitions": [
          {
            "name": "QUESTION",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    QUESTION_Table = DWH_SUSTAIN_ID_Schema{[Name=\"QUESTION\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(QUESTION_Table,{\"DOCUMENT_ID\", \"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SITE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bec9b009-336f-4860-9c9b-ce07b7255dc6",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a950155-1552-42cc-8d24-4289f9fb8217",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "COUNTRY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07acce01-15f3-41a0-b273-6fd95b4e0496",
            "sourceColumn": "COUNTRY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "COUNTRY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d4c2e81-4a21-472a-bef0-71aff061c0a9",
            "sourceColumn": "COUNTRY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "CODE_SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef5ab20a-28ad-4692-8203-534fe17581ac",
            "sourceColumn": "CODE_SAP",
            "summarizeBy": "none"
          },
          {
            "name": "VERTICAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f39480c1-df64-4dae-8574-3e4e350ae4b4",
            "sourceColumn": "VERTICAL",
            "summarizeBy": "none"
          },
          {
            "name": "MAIN_ACTIVITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51e14842-d441-4471-b9d6-93b4c802f203",
            "sourceColumn": "MAIN_ACTIVITY",
            "summarizeBy": "none"
          },
          {
            "name": "SECONDARY_ACTIVITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "341db1b4-bbb8-4b5e-ae57-268e7b3722f3",
            "sourceColumn": "SECONDARY_ACTIVITY",
            "summarizeBy": "none"
          },
          {
            "name": "TEMPERATURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "027a3ffe-453d-4e8a-ad9f-b7f8c26b7f46",
            "sourceColumn": "TEMPERATURE",
            "summarizeBy": "none"
          },
          {
            "name": "CODE_SITE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d32762e3-121e-4b5b-8781-8ee5a7e7c9e2",
            "sourceColumn": "CODE_SITE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2381ef30-e632-430f-ac21-7363fac02a4a",
        "partitions": [
          {
            "name": "SITE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    SITE_Table = DWH_SUSTAIN_ID_Schema{[Name=\"DIM_SITE\",Kind=\"Table\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(SITE_Table, \"COUNTRY_ID\", \"COUNTRY_ID - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"ID\", \"NAME\", \"COUNTRY_ID\", \"COUNTRY_ID - Copy\", \"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"COUNTRY_ID - Copy\", \"COUNTRY_NAME\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"3\",\"Germany\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"5\",\"Benelux\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"6\",\"Iberia\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"11\",\"Brazil\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"12\",\"Chile\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"1\",\"Argentina\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"2\",\"France\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"4\",\"United Kingdom\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"9\",\"Italy\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"7\",\"Poland\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"8\",\"Romania\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"Argentina0\",\"Argentina\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"ArgentinaBenelux\",\"Reunion Island\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"ArgentinaUnited Kingdom\",\"Taiwan\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"ArgentinaGermany\",\"Indonesia\",Replacer.ReplaceText,{\"COUNTRY_NAME\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Replaced Value14\",{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "THEME",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41a0b876-ff46-49dd-81fc-3e7deb2eff67",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fac3814e-1eb9-433f-bdd5-7c9120b844b3",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "PILLAR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8d5682c-8152-402e-9e93-641c70a1fbb7",
            "sourceColumn": "PILLAR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ORDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e4179668-5335-4740-a2df-ca9900041370",
            "sourceColumn": "ORDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ed387cb-cb58-45fe-9217-0dbd211f0c33",
        "measures": [
          {
            "name": "Translated theme",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES(LANGUAGE_THEME[VALUE])),",
              "    FILTER(",
              "        LANGUAGE_THEME,",
              "        LANGUAGE_THEME[LANGUAGE_ID] = SELECTEDVALUE('LANGUAGE'[ID])",
              "    ),",
              "    USERELATIONSHIP(THEME[ID], LANGUAGE_THEME[THEME_ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "00cc5169-7da8-4690-af29-55303ff9d859"
          }
        ],
        "partitions": [
          {
            "name": "THEME",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    THEME_Table = DWH_SUSTAIN_ID_Schema{[Name=\"THEME\",Kind=\"Table\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(THEME_Table,{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FACT_ANSWERS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "COUNTRY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "c7aeef56-a06d-4c2a-81af-f5dbc553761b",
            "sourceColumn": "COUNTRY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "SITE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "fae01c71-f0f1-4d00-84a4-7f4f96600e63",
            "sourceColumn": "SITE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CAMPAIGN_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "d71a60bb-a2db-43bc-993a-115e45379f71",
            "sourceColumn": "CAMPAIGN_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PILLAR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "c88211f2-476b-4dca-a0eb-2bb539247d1e",
            "sourceColumn": "PILLAR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "THEME_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "f7335d96-fca2-4150-93d8-3670a9c97c3c",
            "sourceColumn": "THEME_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "979dfb0b-bffe-41a3-86c2-14a290cd95bf",
            "sourceColumn": "CATEGORY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "QUESTION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "14cfd092-9c20-40bd-a44b-1917e16fa0a6",
            "sourceColumn": "QUESTION_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ANSWER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "23f3cffc-4f94-40e7-a4db-97b56c742f1e",
            "sourceColumn": "ANSWER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "WEIGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Details",
            "lineageTag": "904109e8-c619-4fae-a3f2-c72b9b3addcd",
            "sourceColumn": "WEIGHT",
            "summarizeBy": "none"
          },
          {
            "name": "CAMPAIGN_SITE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "6f5e9951-0ba1-4f59-a777-a44aff7518a7",
            "sourceColumn": "CAMPAIGN_SITE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ANSWER_VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Details",
            "lineageTag": "96a11b2a-d1cd-4dd9-a75c-497f50768dd4",
            "sourceColumn": "ANSWER_VALUE",
            "summarizeBy": "none"
          },
          {
            "name": "ExtractYearFromAnswer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Details",
            "expression": [
              "",
              "VAR DatePart =",
              "    IF(",
              "        ISERROR(DATEVALUE(LEFT([ANSWER_VALUE], 10))),",
              "        BLANK(),",
              "        LEFT([ANSWER_VALUE], 10)",
              "    )",
              "RETURN",
              "IF(",
              "    NOT(ISBLANK(DatePart)),",
              "    YEAR(DATEVALUE(DatePart)),",
              "    BLANK() // Or use a fallback value like 0 or \"N/A\"",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c2d8a99a-8f8a-4ba2-8e86-ca56a35e4e47",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "9717762e-33ad-4b09-954b-a7f0f35d106b",
        "measures": [
          {
            "name": "RatioQuestionsAnswers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": "DISTINCTCOUNT(FACT_ANSWERS[ANSWER_ID])/DISTINCTCOUNT(FACT_ANSWERS[QUESTION_ID])",
            "lineageTag": "d5190fe1-d044-4e76-bf4f-971b0aab9e47"
          },
          {
            "name": "MaxScore",
            "displayFolder": "Measures",
            "expression": [
              "CALCULATE(",
              "    MAX(ANSWER[MAX_WEIGHT]),",
              "    ALL(SITE),",
              "    ALL(CAMPAIGN)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "efa4c691-ab7a-4074-8bf1-fd92583ab15e"
          },
          {
            "name": "Score",
            "displayFolder": "Measures",
            "expression": [
              "DIVIDE(",
              "    SUMX(FACT_ANSWERS,FACT_ANSWERS[WEIGHT])+0, ",
              "    FACT_ANSWERS[MaxScore]",
              ")"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "52dd8bcc-22a8-4c7d-971f-abb580febbdd"
          },
          {
            "name": "Surface Au Sol",
            "displayFolder": "Measures",
            "lineageTag": "33cb2172-a02f-4e3f-86b7-f33e3248fe4c"
          },
          {
            "name": "NombreQuestionnairesRemplis",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID]),",
              "    CAMPAIGN_SITE[IS_FINISHED] = 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f3c82865-5412-45bb-a044-a329daf77670"
          },
          {
            "name": "NombreTotalQuestionnairesEnvoyes",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "\tDISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0d5d9c6c-8b63-47de-bec7-a0fb7671edb8"
          },
          {
            "name": "RatioRemplisPourcentage",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE(",
              "    [NombreQuestionnairesRemplis],",
              "    [NombreTotalQuestionnairesEnvoyes]",
              ")"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "7dbd4d17-7b0d-42f0-9e4e-d8caf9323aea"
          },
          {
            "name": "NombreQuestionnairesRemplis total for CAMPAIGN_SITE_ID",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "\tDISTINCTCOUNTNOBLANK(FACT_ANSWERS[CAMPAIGN_SITE_ID])",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "TotalForSelectedCategory",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "f5326679-0a79-495e-9a48-b6fb0f954ad2"
          },
          {
            "name": "TotalPointsDisponibles",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "SUMX(",
              "    ANSWER,",
              "    IF(",
              "        ANSWER[IS_NA] = 0,",
              "        ANSWER[WEIGHT],",
              "        0",
              "    )",
              ")"
            ],
            "lineageTag": "ab03ba9b-58ce-4c3e-b711-a7641f6a6f1c"
          },
          {
            "name": "TotalPointsObtenus",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "SUM(FACT_ANSWERS[WEIGHT])"
            ],
            "lineageTag": "b252eedf-d8c3-45e3-b85f-ace7604cb99f"
          },
          {
            "name": "ScoreMoyenGlobalPourcentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE(",
              "    [TotalPointsObtenus],",
              "    [TotalPointsDisponibles],",
              "    0",
              ") * 100"
            ],
            "lineageTag": "124b84bd-039d-4190-9cba-2ca842cdb7b5"
          },
          {
            "name": "NombreReponsesParQuestion",
            "displayFolder": "Measures",
            "expression": [
              "",
              "VAR QuestionSelectionnee = SELECTEDVALUE(QUESTION[ID])",
              "RETURN",
              "    IF(",
              "        ISBLANK(QuestionSelectionnee),",
              "        0, -- Si aucune question n'est sélectionnée",
              "        IF(",
              "            CALCULATE(COUNTROWS(ANSWER), FACT_ANSWERS[QUESTION_ID] = QuestionSelectionnee) = 0,",
              "            0, -- Si la question sélectionnée n'a pas de réponse",
              "            CALCULATE(COUNTROWS(ANSWER), FACT_ANSWERS[QUESTION_ID] = QuestionSelectionnee) -- Retourne le nombre de réponses",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "fcd8a9ef-1b35-4377-90fd-ca1ca40e78ac"
          },
          {
            "name": "TotalResponses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "VAR FilteredAnswers =",
              "    FILTER(",
              "        'FACT_ANSWERS',",
              "        'FACT_ANSWERS'[QUESTION_ID] IN ",
              "            SELECTCOLUMNS(FILTER('QUESTION', 'QUESTION'[CODE] >= \"ID.010\" && 'QUESTION'[CODE] <= \"ID.018\"), \"QUESTION_ID\", 'QUESTION'[ID])",
              "    )",
              "RETURN",
              "    SUMX(",
              "        FilteredAnswers,",
              "        IFERROR(VALUE('FACT_ANSWERS'[ANSWER_VALUE]), 0)",
              "    )"
            ],
            "lineageTag": "4e49ca2f-c889-4f86-b373-6ab268b43cf5"
          },
          {
            "name": "MoyenneScoresParPillier",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        FILTER(FACT_ANSWERS, FACT_ANSWERS[PILLAR_ID] = SELECTEDVALUE(PILLAR[ID])),",
              "        FACT_ANSWERS[WEIGHT]",
              "    )",
              ")"
            ],
            "lineageTag": "cc3d0aef-88fc-4ee6-9240-3257c834270b"
          },
          {
            "name": "MoyenneScoresParPillier_Site",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        FILTER(",
              "            FACT_ANSWERS,",
              "            FACT_ANSWERS[PILLAR_ID] = SELECTEDVALUE(PILLAR[ID]) &&",
              "            FACT_ANSWERS[SITE_ID] = SELECTEDVALUE(SITE[ID])",
              "        ),",
              "        FACT_ANSWERS[WEIGHT]",
              "    )",
              ")"
            ],
            "lineageTag": "ced56a2f-3527-4120-b1a9-d1493ca8b6e7"
          },
          {
            "name": "AvgScore",
            "displayFolder": "Measures",
            "expression": "CALCULATE(AVERAGEX(FACT_ANSWERS,FACT_ANSWERS[Score]), KEEPFILTERS('LANGUAGE'))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "7a105a96-7823-4009-b706-cd9a050d3abc"
          },
          {
            "name": "CountAnswersByYear",
            "displayFolder": "Measures",
            "expression": [
              "",
              "COUNTROWS(",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        NOT(ISBLANK([ExtractYearFromAnswer]))",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "96f35933-2001-4123-86d0-34cee234b489"
          },
          {
            "name": "CountSiteOpenedByYear",
            "displayFolder": "Measures",
            "expression": [
              "CALCULATE(",
              "    SUMX(FACT_ANSWERS,[CountAnswersByYear]),",
              "    QUESTION[CODE] = \"ID.007\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a9300a9f-b12f-463d-912f-a388ac48bef2"
          },
          {
            "name": "CountLastAuditByYear",
            "displayFolder": "Measures",
            "expression": [
              "CALCULATE(",
              "    SUMX(FACT_ANSWERS,[CountAnswersByYear]),",
              "    QUESTION[CODE] = \"ID.027\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fd28287e-2eb7-4656-b93e-479182131353"
          },
          {
            "name": "CountSiteBuiltByYear",
            "displayFolder": "Measures",
            "expression": [
              "CALCULATE(",
              "    SUMX(FACT_ANSWERS,[CountAnswersByYear]),",
              "    QUESTION[CODE] = \"ID.008\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "64e1f30e-5b07-4dcc-959e-5e72ee45a279"
          },
          {
            "name": "Proportion Temperature",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Temperature], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "91244166-c2c7-4666-aa2e-6e2001a51f35"
          },
          {
            "name": "Nombre Energy Management device",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_VALUE]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.019\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "40d113b1-2f95-4977-b5c3-3c8f9e012bdf"
          },
          {
            "name": "Proportion Energy Management Device",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Energy Management device], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "6b509ec3-a0d2-41fe-886d-9b7d050c4ae5"
          },
          {
            "name": "Nombre Energy Storage",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_VALUE]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.020\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "be8818e6-6364-4e74-873c-6323341ac841"
          },
          {
            "name": "Proportion Energy Storage",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Energy Storage], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "bd17c52c-f2df-47ab-9cf7-a90b31f9d116"
          },
          {
            "name": "Nombre Presence generator",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_VALUE]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.021\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "01332992-db70-4e9a-afa2-8510e9d2eebd"
          },
          {
            "name": "Proportion Presence generator",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Presence generator], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "4e897b68-6360-4b09-85a6-3e05ca89f5f4"
          },
          {
            "name": "Nombre Construction type",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_ID]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.022\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f2bc918d-bb33-46c8-9fd4-c23a2163eb0a"
          },
          {
            "name": "Proportion Construction type",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Construction type], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "63178b08-3291-4c9c-8eac-d4bbfc12dfae"
          },
          {
            "name": "Nombre Env Certification",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_ID]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.023\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b5725c24-5037-488c-9327-0a815239d221"
          },
          {
            "name": "Proportion Env certification",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Env Certification], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "c8d61cc0-1318-490b-bc1f-927fd4739076"
          },
          {
            "name": "Nombre Environment Risk Zone",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_VALUE]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.024\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5f91e2a2-76f6-46a5-b9ed-96cfe41e6707"
          },
          {
            "name": "Proportion Environement Risk Zone",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Environment Risk Zone], [Nombre de site], 0)"
            ],
            "lineageTag": "c877b05a-7e4f-4256-96a5-019037c906d3"
          },
          {
            "name": "Nombre Security Building Class",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_ID]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.025\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c28973a0-ce37-4c7b-9e71-cd4dd0641191"
          },
          {
            "name": "Proportion Security Building Class",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Security Building Class], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d64239ed-fb0d-40d6-bd02-e89d49570a7f"
          },
          {
            "name": "Nombre Performance certif energy",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_ID]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.026\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8e3560f3-2be0-487a-868b-ef12b12dd4f1"
          },
          {
            "name": "Proportion Perform Certif Energy",
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Performance certif energy], [Nombre de site], 0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "b8607e43-684e-4b1d-87c8-0c9668177630"
          },
          {
            "name": "Nombre Intramural Canteen",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_VALUE]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.028\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "64046cc6-f2c9-4821-8dfa-b9003805a39e"
          },
          {
            "name": "Proportion Intramural Canteen",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Intramural Canteen], [Nombre de site], 0)"
            ],
            "lineageTag": "62148ac2-fc83-420e-a182-19d31337ff38"
          },
          {
            "name": "Nombre Operation Type",
            "displayFolder": "Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(FACT_ANSWERS[ANSWER_ID]),",
              "    FILTER(",
              "        FACT_ANSWERS,",
              "        RELATED(QUESTION[CODE]) = \"ID.029\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e965e650-3d40-45eb-853d-b46c6852a509"
          },
          {
            "name": "Proportion Operation Type",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Measures",
            "expression": [
              "",
              "DIVIDE([Nombre Operation Type], [Nombre de site], 0)"
            ],
            "lineageTag": "ff52ff3e-d8f8-40b1-9eab-8f8252b0cfe4"
          },
          {
            "name": "Count Answers Questions No ID",
            "displayFolder": "Measures",
            "expression": "CALCULATE(COUNT(FACT_ANSWERS[ANSWER_ID]))",
            "formatString": "0",
            "lineageTag": "ce3e784e-fae9-4b08-8f9a-b1b565fa234f"
          },
          {
            "name": "Proportions Questions No ID",
            "displayFolder": "Measures",
            "expression": "DIVIDE([Count Answers Questions No ID], FILTER(FACT_ANSWERS, SELECTEDVALUE(FACT_ANSWERS[QUESTION_ID]) ), 0)",
            "lineageTag": "4b98c9e2-aab2-47c4-93d9-5e91e20bd066"
          }
        ],
        "partitions": [
          {
            "name": "FACT_ANSWERS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    FACT_ANSWERS_Table = DWH_SUSTAIN_ID_Schema{[Name=\"FACT_ANSWERS\",Kind=\"Table\"]}[Data]",
                "in",
                "    FACT_ANSWERS_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ANSWER",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "440c23f1-d5ab-4b92-8c50-9ee88fb2bcbe",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "LABEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c07890d-ef0b-4d58-a187-d795c8b6f8f8",
            "sourceColumn": "LABEL",
            "summarizeBy": "none"
          },
          {
            "name": "WEIGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a429b3ed-4228-4123-b0f4-20b27854503b",
            "sourceColumn": "WEIGHT",
            "summarizeBy": "none"
          },
          {
            "name": "IS_NA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "23516d4d-20a2-46b6-99a8-775d8aa0454f",
            "sourceColumn": "IS_NA",
            "summarizeBy": "sum"
          },
          {
            "name": "QUESTION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "884c7d71-dcf5-4a7c-a68e-76968cfd7de0",
            "sourceColumn": "QUESTION_ID",
            "summarizeBy": "none"
          },
          {
            "name": "MAX_WEIGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "642653ff-d9ca-4335-b8b7-405fa01082b1",
            "sourceColumn": "MAX_WEIGHT",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5202b6e2-ef0d-497a-9886-850018fe156b",
        "measures": [
          {
            "name": "Translated answer",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES(LANGUAGE_ANSWER[VALUE])),",
              "    FILTER(",
              "        LANGUAGE_ANSWER,",
              "        LANGUAGE_ANSWER[LANGUAGE_ID] = SELECTEDVALUE('LANGUAGE'[ID])",
              "    ),",
              "    USERELATIONSHIP(ANSWER[ID], LANGUAGE_ANSWER[ANSWER_ID])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "de257035-634f-412a-9590-ba7eceacba37"
          }
        ],
        "partitions": [
          {
            "name": "ANSWER",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    ANSWER_Table = DWH_SUSTAIN_ID_Schema{[Name=\"DIM_ANSWER\",Kind=\"Table\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(ANSWER_Table,{\"CREATED_BY\", \"UPDATED_BY\", \"DELETED_BY\", \"CREATED_AT\", \"UPDATED_AT\", \"DELETED_AT\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE_ANSWER",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LANGUAGE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e5c0f42-ee59-4bdd-b2e3-2f97bff030a9",
            "sourceColumn": "LANGUAGE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ANSWER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59b11d00-442d-4b63-b98b-405afc9c1382",
            "sourceColumn": "ANSWER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75b5b7bf-b5ef-4f5c-bdd7-4131ebdc9977",
            "sourceColumn": "VALUE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "18b4b63d-cb10-4606-8821-70116f10554a",
        "partitions": [
          {
            "name": "LANGUAGE_ANSWER",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_ANSWER_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE_ANSWER\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_ANSWER_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE_QUESTION",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LANGUAGE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "416922a6-fa3a-434f-a02f-f6ef150c3d0a",
            "sourceColumn": "LANGUAGE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "QUESTION_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d6ff74c-8d3c-4ad2-b793-29f39b68fd0c",
            "sourceColumn": "QUESTION_ID",
            "summarizeBy": "count"
          },
          {
            "name": "LABEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba2236a6-8856-4928-9a63-afb52cd10a30",
            "sourceColumn": "LABEL",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPTION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27efe00d-6eef-40ed-bba6-6eb6c629855a",
            "sourceColumn": "DESCRIPTION",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "96255a06-f5c1-4184-a9e7-8492190817a8",
        "partitions": [
          {
            "name": "LANGUAGE_QUESTION",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_QUESTION_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE_QUESTION\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_QUESTION_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d1304310-2796-47bf-858e-84eba8b8f5f4",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8eaa95b3-2f46-482c-b22e-f794bd92abf2",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53be3333-67f9-4364-b1f4-d91ec792c953",
            "sourceColumn": "CODE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "835bc4cf-831e-4f22-bec4-46afcbe79513",
        "partitions": [
          {
            "name": "LANGUAGE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE_PILLAR",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LANGUAGE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff006e5c-9025-42e3-9afb-b387807872f5",
            "sourceColumn": "LANGUAGE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PILLAR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d465973-e716-4567-9b69-3f3a929294f1",
            "sourceColumn": "PILLAR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "027fa83c-8e85-44e6-b159-929098c4a368",
            "sourceColumn": "VALUE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e7f22cff-14b6-4db3-b939-9c0630c866c4",
        "partitions": [
          {
            "name": "LANGUAGE_PILLAR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_PILLAR_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE_PILLAR\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_PILLAR_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DATE",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FULLDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a9d75380-b31f-437c-9cda-1eed27db850a",
            "sourceColumn": "FULLDATE",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "21bad801-f584-4e1b-ae35-040aeff98e73",
            "sourceColumn": "YEAR_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "MONTH_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "c108e89c-f6a6-49e8-b88a-f2694883bf0e",
            "sourceColumn": "MONTH_NUMBER",
            "summarizeBy": "none"
          },
          {
            "name": "MONTH_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f703760-edae-4557-98a0-1f2260b51701",
            "sourceColumn": "MONTH_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "DAY_OF_MONTH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f00bcf78-8ff6-4914-857d-5af671fb4059",
            "sourceColumn": "DAY_OF_MONTH",
            "summarizeBy": "none"
          },
          {
            "name": "DAY_OF_WEEK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "7f0cd447-fc2e-4a5c-b8c1-ac3f6b09e749",
            "sourceColumn": "DAY_OF_WEEK",
            "summarizeBy": "none"
          },
          {
            "name": "WEEK_OF_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "886ff78c-f8d0-4c8e-8703-7afa7753754a",
            "sourceColumn": "WEEK_OF_YEAR",
            "summarizeBy": "none"
          },
          {
            "name": "DAY_OF_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "2ee8c28a-304c-4597-a833-8f03d4abbe2f",
            "sourceColumn": "DAY_OF_YEAR",
            "summarizeBy": "none"
          },
          {
            "name": "DATE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1f7a907f-94e0-4afa-b572-499b06444ba6",
            "sourceColumn": "DATE_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f8be9aec-5c79-4b88-967e-629ac5779ecf",
        "partitions": [
          {
            "name": "DATE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"idlogistics.west-europe.azure.snowflakecomputing.com\",\"WH_PRD_GRP\"),",
                "    DB_PRD_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_PRD_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    DATE_Table = DWH_SUSTAIN_ID_Schema{[Name=\"DIM_DATE\",Kind=\"Table\"]}[Data]",
                "in",
                "    DATE_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE_CATEGORY",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LANGUAGE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce9fb05b-5426-43ae-b1ca-444c6dff5310",
            "sourceColumn": "LANGUAGE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ac448db-d03f-4109-825c-2af827a3384b",
            "sourceColumn": "CATEGORY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33114ad2-4984-483e-bef4-bbecf60b12e1",
            "sourceColumn": "VALUE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "70e08896-4bf7-4a17-a26a-00d15841e34f",
        "partitions": [
          {
            "name": "LANGUAGE_CATEGORY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=DB_NAME,Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_CATEGORY_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE_CATEGORY\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_CATEGORY_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LANGUAGE_THEME",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LANGUAGE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c778324c-993a-42c7-b810-87b8ce9d1cde",
            "sourceColumn": "LANGUAGE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "THEME_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02cc85af-ecb0-4ba6-8495-ece296e010fa",
            "sourceColumn": "THEME_ID",
            "summarizeBy": "none"
          },
          {
            "name": "VALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bb6cba6-ad08-4cc6-9e4b-c496b9137527",
            "sourceColumn": "VALUE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d6b92423-4b08-493d-ad41-d4ae5d783d1e",
        "partitions": [
          {
            "name": "LANGUAGE_THEME",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"UY39352-IDLOGISTICS.snowflakecomputing.com\",\"WH_DEV_GRP\"),",
                "    DB_DEV_GRP_Database = Source{[Name=#\"DB_NAME\",Kind=\"Database\"]}[Data],",
                "    DWH_SUSTAIN_ID_Schema = DB_DEV_GRP_Database{[Name=\"DWH_SUSTAIN_ID\",Kind=\"Schema\"]}[Data],",
                "    LANGUAGE_THEME_Table = DWH_SUSTAIN_ID_Schema{[Name=\"LANGUAGE_THEME\",Kind=\"Table\"]}[Data]",
                "in",
                "    LANGUAGE_THEME_Table"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}